######################################################################
# Automatically generated by qmake (3.0) Thu Dec 8 17:47:35 2016
######################################################################

TEMPLATE = app
TARGET = somedemo
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    whatelse.cpp

HEADERS += \
    whatelse.h
